name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Upload .env to EC2
      run: |
        echo "${{ secrets.EC2_ENV_FILE }}" | ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'mkdir -p ~/daw-films && cat > ~/daw-films/.env'

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          cd /home/${{ secrets.EC2_USER }}

          # Clonar si no existe
          if [ ! -d daw-films ]; then
            echo "Clonando repositorio..."
            git clone https://github.com/JesusJimenez01/daw_films.git daw_films
          fi

          cd daw-films

          echo "Estado Git actual:"
          git status
          git remote -v

          # Apagar contenedores antes de desplegar
          echo "Apagando contenedores antiguos..."
          docker compose down

          # Actualizar desde main
          git reset --hard
          git pull origin main

          # Ejecutar script de despliegue
          chmod +x deploy.sh
          ./deploy.sh

          # Limpiar imágenes no usadas
          docker system prune -f
        EOF

    - name: Health Check
      run: |
        echo "Esperando a que la app levante..."
        sleep 30
        curl -f http://dawfilms.jesus-jimenez.tech || exit 1


