name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Upload .env to EC2
      run: |
        echo "${{ secrets.EC2_ENV_FILE }}" | ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'mkdir -p ~/daw_films && cat > ~/daw_films/.env'

    - name: Deploy to EC2
      run: |
        export EC2_USER=${{ secrets.EC2_USER }}
        ssh -i ~/.ssh/id_rsa $EC2_USER@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          cd /home/$EC2_USER

          # Clonar si no es un repo Git válido
          if [ ! -d daw_films/.git ]; then
            echo "⚠️ Clonando repositorio porque no es un repo Git"
            rm -rf daw_films
            git clone https://github.com/JesusJimenez01/daw_films.git daw_films
          fi

          cd daw_films

          echo "Estado Git actual:"
          git status
          git remote -v

          # Apagar contenedores antiguos
          echo "Apagando contenedores antiguos..."
          docker compose down || true

          # Obtener últimos cambios
          git reset --hard
          git pull origin main

          # Ejecutar script de despliegue
          chmod +x deploy.sh
          ./deploy.sh

          # Limpiar imágenes no utilizadas
          docker system prune -f
        EOF

    - name: Health Check
      run: |
        echo "Esperando a que la app levante..."
        for i in {1..10}; do
          if curl -f http://dawfilms.jesus-jimenez.tech; then
            echo "✅ La app está arriba"
            exit 0
          fi
          echo "Esperando..."
          sleep 5
        done
        echo "❌ La app no respondió a tiempo"
        exit 1



