name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          cd /home/${{ secrets.EC2_USER }}

          if [ ! -d daw-films ]; then
            echo "Clonando repositorio..."
            git clone https://github.com/JesusJimenez01/daw_films.git daw-films
          fi

          cd daw-films

          echo "Estado Git actual:"
          git status
          git remote -v

          if [ -f .env ]; then
            cp .env .env.backup
          fi

          echo "Apagando contenedores antiguos..."
          docker compose down --remove-orphans

          echo "Actualizando código..."
          git reset --hard
          git pull origin main

          if [ -f .env.backup ]; then
            mv .env.backup .env
          fi

          echo "Ejecutando despliegue..."
          chmod +x deploy.sh
          ./deploy.sh

          echo "Limpiando recursos Docker no utilizados..."
          docker system prune -af
        EOF

    - name: Health Check
      run: |
        echo "Esperando a que la app levante..."
        sleep 30
        curl -f https://dawfilms.jesus-jimenez.tech || exit 1

